# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/ThadBookstoreOrder/api/categories
Accept: application/json

###
# curl 'http://localhost:8080/ThadBookstoreOrder/api/orders'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Cookie: JSESSIONID=D34EFBED3C337924948FE11D33708CA4'
#  -H 'Origin: http://localhost:8080'
#  -H 'Referer: http://localhost:8080/ThadBookstoreOrder/checkout/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1001,"title":"Little Dorrit","author":"Charles Dickens","description":"","price":599,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":3},{"book":{"bookId":1022,"title":"Dune","author":"Frank Herbert","description":"","price":699,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1005},"quantity":3}]},"customerForm":{"name":"Steve","address":"1233","phone":"4085551212","email":"steve@main.com","ccNumber":"4444333322221111","ccExpiryMonth":"6","ccExpiryYear":2024}}'
POST http://localhost:8080/ThadBookstoreOrder/api/orders
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: JSESSIONID=D34EFBED3C337924948FE11D33708CA4
Origin: http://localhost:8080
Referer: http://localhost:8080/ThadBookstoreOrder/checkout/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1001,
          "title": "Little Dorrit",
          "author": "Charles Dickens",
          "description": "",
          "price": 599,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 3
      },
      {
        "book": {
          "bookId": 1022,
          "title": "Dune",
          "author": "Frank Herbert",
          "description": "",
          "price": 699,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1005
        },
        "quantity": 3
      }
    ]
  },
  "customerForm": {
    "name": "Steve",
    "address": "1233",
    "phone": "4085551212",
    "email": "steve@main.com",
    "ccNumber": "4444333322221111",
    "ccExpiryMonth": "6",
    "ccExpiryYear": 2024
  }
}

###
# curl 'http://localhost:8080/ThadBookstoreOrder/api/orders'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Cookie: JSESSIONID=D34EFBED3C337924948FE11D33708CA4'
#  -H 'Origin: http://localhost:8080'
#  -H 'Referer: http://localhost:8080/ThadBookstoreOrder/checkout/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1001,"title":"Little Dorrit","author":"Charles Dickens","description":"","price":599,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":3},{"book":{"bookId":1022,"title":"Dune","author":"Frank Herbert","description":"","price":699,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1005},"quantity":3}]},"customerForm":{"name":"Steve","address":"1233","phone":"4085551212","email":"steve@main.com","ccNumber":"4444333322221111","ccExpiryMonth":"8","ccExpiryYear":2024}}'
POST http://localhost:8080/ThadBookstoreOrder/api/orders
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: JSESSIONID=D34EFBED3C337924948FE11D33708CA4
Origin: http://localhost:8080
Referer: http://localhost:8080/ThadBookstoreOrder/checkout/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1001,
          "title": "Little Dorrit",
          "author": "Charles Dickens",
          "description": "",
          "price": 599,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 3
      },
      {
        "book": {
          "bookId": 1022,
          "title": "Dune",
          "author": "Frank Herbert",
          "description": "",
          "price": 699,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1005
        },
        "quantity": 3
      }
    ]
  },
  "customerForm": {
    "name": "Steve",
    "address": "1233",
    "phone": "4085551212",
    "email": "steve@main.com",
    "ccNumber": "4444333322221111",
    "ccExpiryMonth": "8",
    "ccExpiryYear": 2024
  }
}

###










